# SPDX-FileCopyrightText: 2020-2022 Johannes Hampp
#
# SPDX-License-Identifier: GPL-3.0-or-later

scenarios:
  annually_with_csp:
    import_profile: "constant"
    import_buffer: "annually"
    supply_technologies: ["csp-tower", "offwind", "onwind", "solar-utility"]

  annually_without_csp:
    import_profile: "constant"
    import_buffer: "annually"
    supply_technologies: ["offwind", "onwind", "solar-utility"]

  quaterly_with_csp:
    import_profile: "constant"
    import_buffer: "quaterly"
    supply_technologies: ["csp-tower", "offwind", "onwind", "solar-utility"]

  quaterly_without_csp:
    import_profile: "constant"
    import_buffer: "quaterly"
    supply_technologies: ["offwind", "onwind", "solar-utility"]

  monthly_with_csp:
    import_profile: "constant"
    import_buffer: "monthly"
    supply_technologies: ["csp-tower", "offwind", "onwind", "solar-utility"]

  monthly_without_csp:
    import_profile: "constant"
    import_buffer: "monthly"
    supply_technologies: ["offwind", "onwind", "solar-utility"]

  biweekly_with_csp:
    import_profile: "constant"
    import_buffer: "biweekly"
    supply_technologies: ["csp-tower", "offwind", "onwind", "solar-utility"]

  biweekly_without_csp:
    import_profile: "constant"
    import_buffer: "biweekly"
    supply_technologies: ["offwind", "onwind", "solar-utility"]

  weekly_with_csp:
    import_profile: "constant"
    import_buffer: "weekly"
    supply_technologies: ["csp-tower", "offwind", "onwind", "solar-utility"]

  weekly_without_csp:
    import_profile: "constant"
    import_buffer: "weekly"
    supply_technologies: ["offwind", "onwind", "solar-utility"]

  daily_with_csp:
    import_profile: "constant"
    import_buffer: "daily"
    supply_technologies: ["csp-tower", "offwind", "onwind", "solar-utility"]

  daily_without_csp:
    import_profile: "constant"
    import_buffer: "daily"
    supply_technologies: ["offwind", "onwind", "solar-utility"]

  unbuffered_with_csp:
    import_profile: "constant"
    import_buffer: False
    supply_technologies: ["csp-tower", "offwind", "onwind", "solar-utility"]

  unbuffered_without_csp:
    import_profile: "constant"
    import_buffer: False
    supply_technologies: ["offwind", "onwind", "solar-utility"]