name: trace
channels:
- conda-forge
- bioconda
- https://conda.anaconda.org/gurobi
dependencies:
- python
- ipython
- ipykernel

  # Managing data
- xarray
- rioxarray
- richdem
- dask
- pandas
- geopandas
- geoviews
- numpy
- gdal
- zip

  # Visualisation
- matplotlib
- seaborn
- hvplot

# AUX for bokeh plot export
- selenium
- firefox
- geckodriver

  # Modelling framework
- pycountry
- pypsa

  # Data retrieval
- cdsapi

  # Auxiliary packages for atlite (explicitly required from conda-forge while it is installed via pip)
- rasterio
- fiona
- bottleneck

  # Workflow management
- snakemake
- snakefmt
- notebook

  # Read Julia files
- h5py

  # Solver
- gurobi

  # Code style and quality checks
- pre-commit
#- nbformat<5.1 # Until https://github.com/snakemake/snakemake/issues/1032 is resolved

- pip

- pip:
    # Modelling Renewables, via pip
    # while atlite https://github.com/PyPSA/atlite/commit/e409dddd632bf9711188de068a2824ee31ace81f is not on conda-forge
  - git+https://github.com/PyPSA/atlite
