name: trace
channels:
- conda-forge
- gurobi
- bioconda
dependencies:
- python
- ipython
- ipykernel

  # Managing data
- xarray
- rioxarray
- richdem
- dask
- pandas
- geopandas
- geoviews
- numpy
- gdal
- zip

  # Visualisation
- matplotlib
- seaborn
- hvplot

# AUX for bokeh plot export
- selenium
- firefox
- geckodriver

  # Modelling framework
- pycountry
- pypsa
- atlite

  # Data retrieval
- cdsapi

  # Auxiliary packages for atlite (explicitly required from conda-forge while it is installed via pip)
- rasterio
- fiona
- bottleneck

  # Workflow management
- snakemake
- snakefmt
- notebook
- nbconvert

  # Read Julia files
- h5py

  # Solver
- gurobi

  # Code style and quality checks
- pre-commit
- reuse

- pip
