name: trace
channels:
  - conda-forge
  - bioconda
  - https://conda.anaconda.org/gurobi
dependencies:
  - python
  - ipython
  - ipykernel

  # Managing data
  - xarray
  - dask
  - pandas
  - geopandas
  - numpy
  - gdal

  # Visualisation
  - matplotlib
  - seaborn
  - hvplot

  # Modelling framework
  - pypsa

  # Data retrieval
  - cdsapi

  # Auxiliary packages for atlite (explicitly required from conda-forge while it is installed via pip)
  - rasterio
  - fiona
  - bottleneck

  # Workflow management
  - snakemake
  - snakefmt

  # Read Julia files
  - h5py

  # Solver
  - gurobi

  # Code style and quality checks 
  - pre-commit

  - pip:
    # Modelling Renewables, via pip
    # while atlite https://github.com/PyPSA/atlite/commit/e409dddd632bf9711188de068a2824ee31ace81f is not on conda-forge
    - git+https://github.com/PyPSA/atlite