name: trace
channels:
- conda-forge
- gurobi
- bioconda
dependencies:
- python
- ipython
- ipykernel

  # Managing data
- xarray
- dask
- pandas
- geopandas
- numpy

  # Visualisation
- matplotlib
- seaborn
- hvplot
- tqdm

  # Modelling framework
- pypsa
- atlite

  # Data retrieval
- cdsapi

  # Auxiliary packages for atlite (explicitly required from conda-forge while it is installed via pip)
- rasterio
- fiona
- bottleneck

  # Workflow management
- snakemake
- snakefmt
- notebook
- nbconvert

  # Read Julia files
- h5py

  # Solver
- gurobi

  # Code style and quality checks 
- pre-commit
